set number
set autoindent
set smartindent
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set backspace=2
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1

inoremap <C-e> <End>
inoremap <C-f> <C-x><C-o>
nnoremap te :tabedit
nnoremap <A-Left> :tabp<CR>
nnoremap <A-Right> :tabn<CR>

autocmd VimEnter * hi MatchParen ctermbg=darkblue
autocmd BufWritePre * %s/\s\+$//e
colorscheme dante

set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'gkz/vim-ls'
call vundle#end()

filetype indent on
filetype plugin on
syntax on
