set autoindent
set backspace=2
set encoding=utf-8
set expandtab
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set nofixendofline
set number
set shiftwidth=4
set smartindent
set smarttab
set tabstop=4
set toolbariconsize=huge

colorscheme koehler
filetype indent on
filetype plugin on
syntax on

autocmd BufWritePre * %s/\s\+$//e
autocmd VimEnter * hi MatchParen ctermbg=darkblue

nnoremap <S-Tab> :tabp<CR>
nnoremap <Tab> :tabn<CR>
nnoremap te :tabedit
