set autoindent
set backspace=2
set encoding=utf-8
set expandtab
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set number
set shiftwidth=4
set smartindent
set smarttab
set tabstop=4

colorscheme desert
filetype indent on
filetype plugin on
syntax on

autocmd BufWritePre * %s/\s\+$//e
autocmd VimEnter * hi MatchParen ctermbg=darkblue

nnoremap <A-Left> :tabp<CR>
nnoremap <A-Right> :tabn<CR>
nnoremap te :tabedit
