#!/bin/sh
export LC_CTYPE="zh_CN.UTF-8"
export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE=fcitx
export GTK_IM_MODULE=fcitx

im-config -l
im-config -o fcitx
im-config -n fcitx

echo "DESKTOP DOWNLOAD TEMPLATES PUBLICSHARE DOCUMENTS MUSIC PICTURES VIDEOS" \
    | xargs -I {} xdg-user-dirs-update --set {} ~

mate-session 2>/dev/null &
awesome
