#!/bin/sh
export LC_CTYPE="zh_CN.UTF-8"
export XMODIFIERS="@im=fcitx"
export QT_IM_MODULE=fcitx
export GTK_IM_MODULE=fcitx

xdg-user-dirs-update --set DESKTOP ~
xdg-user-dirs-update --set DOCUMENTS ~
xdg-user-dirs-update --set DOWNLOAD ~
xdg-user-dirs-update --set MUSIC ~
xdg-user-dirs-update --set PICTURES ~
xdg-user-dirs-update --set PUBLIC ~
xdg-user-dirs-update --set SHARE ~
xdg-user-dirs-update --set TEMPLATES ~
xdg-user-dirs-update --set VIDEOS ~

im-config -l &
im-config -o fcitx &
im-config -n fcitx &
(sleep 2 && fcitx -d) &

mate-session 2>>/tmp/xinit.err &
mate-settings-daemon 2>>/tmp/xinit.err &
awesome
