- name: start container
  shell: >-
    docker run -d
    --name socks
    --restart always
    --network host
    --dns 1.2.4.8
    --dns 8.8.8.8
    --log-opt max-file=10
    --log-opt max-size=100m
    -v {{role_path}}/files:/opt/proxy
    -w /opt/proxy
    --entrypoint /usr/local/bin/npm
    docker.io/wizawu/proxy:latest
    run start
