#!/bin/sh

# run with sudo

set -e -x

HOME="/home/wiza"
PWD=$(cd $(dirname $0) && pwd)

DEB_MIR="deb http://mirrors.163.com/debian/ sid main contrib non-free"
echo $DEB_MIR > /etc/apt/sources.list
apt-get update

apt-get install -y --no-install-recommends \
                linux-headers-amd64 linux-image-amd64 \
                sudo make unzip unrar \
                xfce4-session xorg xscreensaver \
                awesome awesome-extra \
                wpasupplicant

if [ $# -eq 1 ] && [ $1 = '-full' ]; then
apt-get install -y --no-install-recommends \
                alsa-base alsa-oss alsa-tools alsa-utils \
                ack-grep axel cmake dbus di dstat \
                erlang-base-hipe erlang-inets erlang-xmerl \
                fio fiu-utils g++ gcc-doc \
                hdparm htop httpie httrack iftop iotop \
                lftp linux-tools lm-sensors lshw mtr manpages-dev \
                nmap ntfs-3g ntp p7zip-full parallel pcmanfm \
                pm-utils rsync samba scim smbclient ssh strace \
                sysstat tcpdump time tmux tree tsocks \
                valgrind vifm vim-gtk vlc vsftpd wput xsel \
                xfce4-terminal
fi

VUNDLE=$HOME/.vim/bundle/vundle
mkdir -p $VUNDLE && rm -r $VUNDLE
git clone -b master --depth 1 https://github.com/gmarik/vundle.git $VUNDLE

ln -sf $PWD/gccrun          /usr/bin/
ln -sf $PWD/shadowsocks     /usr/bin/
ln -sf $PWD/keycool.sh      /usr/bin/keycool
ln -sf $PWD/.xinitrc        $HOME/
ln -sf $PWD/.bashrc         $HOME/
ln -sf $PWD/.vimrc          $HOME/
ln -sf $PWD/.dircolors      $HOME/
ln -sf $PWD/.tmux.conf      $HOME/
ln -sf $PWD/.gitconfig      $HOME/

mkdir -p $HOME/.vim/colors
cp $PWD/dante.vim           $HOME/.vim/colors/

set +x

echo "apt-get install wicd-gtk"

exit 0

# useful tools
# getconf
# google-perftools
# hdparm --fibmap
# ipcs
# libhugetlbfs    # hugeadm, hugectl, pagesize
# losetup
# lscpu
# lsof
# lsusb
# mdadm
# ncat
# perf
# pmap
# pstree
# pt-summary    # wget http://percona.com/get/pt-summary
# setxkbmap
# ss
# stat
# xev
# xmodmap
