- hosts: localhost
  vars_prompt:
    - name: agree
      prompt: Cancel the play with CTRL+C or continue with ENTER

  tasks:
    - name: create group
      group: name=docker

    - name: create user
      user:
        name: "{{user}}"
        groups:
          - docker
          - root
          - video
        shell: /bin/bash

    - name: change file mode of this repo
      file:
        dest: /home/{{user}}/.sysconf
        state: directory
        recurse: true
        owner: "{{user}}"

    - name: locale-gen
      locale_gen: name={{item}} state=present
      with_items:
        - en_US.UTF-8
        - zh_CN
        - zh_CN.GB18030
        - zh_CN.GBK
        - zh_CN.UTF-8

    - name: hold libc6
      command: apt-mark hold libc6

    - name: create symbolic link to apt sources.list
      file:
        src: /home/{{user}}/.sysconf/etc/apt/sources.list.d
        dest: /etc/apt/sources.list.d
        state: link
        force: true

    - name: import apt keys
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: "{{item}}"
      with_items:
        - 7EA0A9C3F273FCD8 # docker
        - E88979FB9B30ACF2 # chrome
        - EB3E94ADBE1229CF # vscode

    - name: install apt packages
      apt:
        update_cache: true
        install_recommends: false
        name:
          - acpi
          - alsa-oss
          - alsa-tools
          - alsa-utils
          - apache2-utils
          - bash-completion
          - cifs-utils
          - colortail
          - debootstrap
          - dnsutils
          - dstat
          - entr
          - expect
          - f2fs-tools
          - fio
          - fiu-utils
          - fuse-overlayfs
          - gcp
          - glusterfs-client
          - grub2-common
          - haproxy
          - hdparm
          - hsetroot
          - im-config
          - lftp
          - libfuse2
          - lm-sensors
          - locate
          - lshw
          - lsof
          - m4
          - make
          - manpages-dev
          - nethogs
          - network-manager
          - nfs-common
          - nginx
          - nmap
          - nodejs
          - ntfs-3g
          - p7zip-full
          - parallel
          - pppoeconf
          - psmisc
          - pulseaudio
          - putty-tools
          - rinetd
          - rlwrap
          - rsync
          - sntp
          - software-properties-common
          - ssh
          - sshfs
          - sshpass
          - strace
          - supervisor
          - syslog-ng
          - sysstat
          - systemd-sysv
          - tlp
          - tlp-rdw
          - util-linux-extra
          - wpasupplicant

    - name: check built-in tools
      shell: command -v {{item}}
      with_items:
        - getconf
        - ipcs
        - losetup
        - lscpu
        - lsusb
        - pmap
        - trap

    - include_tasks: tasks/command.yml
    - include_tasks: tasks/desktop.yml
    - include_tasks: tasks/vscode.yml
    - include_tasks: tasks/pip.yml
    - include_tasks: tasks/npm.yml
    - include_tasks: tasks/cleanup.yml

    - name: create etc directories
      file: dest=/{{item}} state=directory recurse=yes
      with_items:
        - etc/X11/xorg.conf.d
        - etc/apt/apt.conf.d
        - etc/fonts/conf.d
        - etc/opt/chrome/policies/managed
        - etc/security/limits.d
        - etc/supervisor/conf.d
        - etc/xdg/awesome

    - name: remove old font config
      shell: rm -f /etc/fonts/conf.d/*

    - name: create symbolic link to global config
      file: src=/home/{{user}}/.sysconf/{{item}} dest=/{{item}} state=link force=yes
      with_items:
        - etc/X11/xorg.conf.d/99-synaptics.conf
        - etc/apt/apt.conf.d/99default
        - etc/docker/daemon.json
        - etc/fonts/conf.d/99-default.conf
        - etc/opt/chrome/policies/managed/blocklist.json
        - etc/rc.local
        - etc/xdg/awesome/rc.lua

    - name: create template config
      template: src={{item}}.tpl dest=/{{item}} mode=0440
      with_items:
        - etc/security/limits.d/default.conf
        - etc/sudoers.d/default

    - name: remove font dir
      lineinfile:
        dest: /etc/fonts/fonts.conf
        regexp: '^\s{0,}<dir'
        state: absent

    - name: add font dir
      lineinfile:
        dest: /etc/fonts/fonts.conf
        line: "\t{{item}}"
        insertafter: "<fontconfig"
      with_items:
        - "<dir>~/.fonts</dir>"

    - name: disable NetworkManager dns
      lineinfile:
        dest: /etc/NetworkManager/NetworkManager.conf
        regexp: '^dns\s{0,}='
        line: "dns=none"
        insertafter: "[main]"
      ignore_errors: true

    - name: restart NetworkManager
      service:
        name: NetworkManager
        state: restarted
      ignore_errors: true

    - name: update systemd logind.conf
      lineinfile:
        dest: /etc/systemd/logind.conf
        regexp: '^{{item.key}}\s{0,}='
        line: "{{item.key}}={{item.value}}"
      with_items:
        - { key: "HandleLidSwitch", value: "ignore" }
        - { key: "HandlePowerKey", value: "suspend" }

    - name: configure kernel parameters
      sysctl:
        name: "{{item.name}}"
        value: "{{item.value}}"
      with_items:
        - name: fs.inotify.max_user_watches
          value: 524288
        - name: kernel.pid_max
          value: 999999
        # async-profiler
        - name: kernel.kptr_restrict
          value: 0
        - name: kernel.perf_event_paranoid
          value: 1

    - name: create symbolic link to user config
      shell: |
        dirname /home/{{user}}/.{{item}} | xargs mkdir -p
        ln -sf /home/{{user}}/.sysconf/dotfiles/{{item}} /home/{{user}}/.{{item}}
      become: true
      become_user: "{{user}}"
      with_items:
        - bashrc
        - gitconfig
        - gradle/gradle.properties
        - sqliterc
        - ssh/config
        - tmux.conf
        - vimrc
        - xinitrc

    - name: copy modified background
      copy:
        src: dotfiles/config/background.png
        dest: /usr/share/awesome/themes/default/background.png
        remote_src: true
