---
- hosts: localhost
  remote_user: root

  tasks:
  - name: check user
    user: name={{user}} state=present group=root shell=/bin/bash

  - name: locale-gen
    locale_gen: name={{item}} state=present
    with_items:
    - en_US.UTF-8
    - zh_CN
    - zh_CN.GB18030
    - zh_CN.GBK
    - zh_CN.UTF-8

  - name: copy sources.list
    copy: src=etc/sources.list dest=/etc/apt/sources.list mode=0644

  - name: apt-get update and upgrade
    apt: update_cache=yes upgrade=safe

  - name: install packages
    apt: name={{item}} state=present
    with_items:
    - ack-grep
    - alsa-base
    - alsa-oss
    - alsa-tools
    - alsa-utils
    - autossh
    - awesome
    - awesome-extra
    - axel
    - cmake
    - colortail
    - dbus
    - debootstrap
    - default-jdk
    - di
    - dstat
    - entr
    - erlang-base-hipe
    - erlang-inets
    - erlang-xmerl
    - fcitx
    - fcitx-googlepinyin
    - fio
    - fiu-utils
    - fping
    - g++
    - gcc-doc
    - google-perftools
    - gtk3-engines-xfce
    - gufw
    - hdparm
    - hsetroot
    - htop
    - httpie
    - httrack
    - iftop
    - iotop
    - leafpad
    - lftp
    - linux-headers-amd64
    - linux-image-amd64
    - linux-tools
    - lm-sensors
    - lshw
    - make
    - manpages-dev
    - mdadm
    - mtr
    - mupdf
    - mycli
    - nginx
    - nmap
    - ntfs-3g
    - ntpdate
    - p7zip-full
    - parallel
    - pcmanfm
    - pm-utils
    - pppoeconf
    - psmisc
    - rinetd
    - rlwrap
    - rsync
    - samba
    - smbclient
    - smplayer
    - ssh
    - sshpass
    - strace
    - sudo
    - sysstat
    - systemd-sysv
    - tcpdump
    - time
    - tmux
    - tree
    - tsocks
    - unrar
    - unzip
    - valgrind
    - viewnior
    - vifm
    - vim-gtk
    - vsftpd
    - wpasupplicant
    - wput
    - x11-xkb-utils
    - x11-xserver-utils
    - xclip
    - xdg-user-dirs
    - xfce4-screenshooter
    - xfce4-session
    - xfce4-terminal
    - xorg
    - xsel

  - name: check built-in tools
    shell: which {{item}} || echo "missing" {{item}}
    with_items:
    - getconf
    - ipcs
    - losetup
    - lscpu
    - lsof
    - lsusb
    - perf
    - pmap
    - trap

  - name: add user to sudoers
    template: src=templates/sudoers dest=/etc/sudoers.d/{{user}} mode=0440

  - name: download pt-summary
    get_url: url=http://percona.com/get/pt-summary dest=/usr/bin/pt-summary mode=0755

  - name: download this repo
    git: repo=https://github.com/wizawu/wizacfg.git dest=/home/{{user}}/.wizacfg
    become: true
    become_user: "{{user}}"

  - name: create symbolic links
    file: src=/home/{{user}}/.wizacfg/etc/{{item.src}} dest={{item.dest}} state=link force=yes
    with_items:
    - {src: "dante.vim",        dest: "/usr/share/vim/vim74/colors/dante.vim"}
    - {src: "nginx.conf",       dest: "/etc/nginx/modules-enabled/nginx.conf"}
    - {src: "rc.lua-3.5",       dest: "/etc/xdg/awesome/rc.lua"}
    - {src: "wlan0",            dest: "/etc/network/interfaces.d/wlan0"}

  - name: create directories
    file: dest=/home/{{user}}/{{item}} state=directory recurse=yes owner={{user}}
    with_items:
    - .config/Code/User
    - .config/fontconfig
    - .vim/bundle

  - name: create symbolic link to dotfiles
    file: src=/home/{{user}}/.wizacfg/dotfiles/{{item}} dest=/home/{{user}}/.{{item}} state=link force=yes owner={{user}}
    with_items:
    - asoundrc
    - bashrc
    - config/Code/User/keybindings.json
    - config/Code/User/settings.json
    - config/fontconfig/fonts.conf
    - dircolors
    - gitconfig
    - tmux.conf
    - vimrc
    - xinitrc

  - name: clone vundle
    git:
      repo: git@github.com:VundleVim/Vundle.vim.git
      dest: /home/{{user}}/.vim/bundle/Vundle.vim
      clone: yes
      force: yes
      depth: 1

  - name: remove xfce panel and desktop
    apt: name={{item}} state=absent
    with_items:
    - xfce4-panel
    - xfdesktop4
    - xscreensaver
