---
- hosts: localhost
  remote_user: root

  tasks:
  - name: check user
    user: name={{user}} state=present group=root shell=/bin/bash

  - name: clone repo
    git: repo=https://github.com/wizawu/wizacfg.git dest=/home/{{user}}/.wizacfg
    become: true
    become_user: "{{user}}"

  - name: locale-gen
    locale_gen: name={{item}} state=present
    with_items:
    - en_US.UTF-8
    - zh_CN
    - zh_CN.GB18030
    - zh_CN.GBK
    - zh_CN.UTF-8

  - name: create symbolic link to apt sources.list
    file: src=/home/{{user}}/.wizacfg/{{item}} dest=/{{item}} state=link force=yes
    with_items:
    - etc/apt/sources.list

  - name: add apt keys
    apt_key: keyserver=keyserver.ubuntu.com id={{item}}
    with_items:
    - F1656F24C74CD1D8      # mariadb
    - 1655A0AB68576280      # node
    - 1397BC53640DB551      # chrome
    - 7638D0442B90D010      # debian
    - EB3E94ADBE1229CF      # vscode

  - name: install apt packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
    - ack-grep
    - alsa-oss
    - alsa-tools
    - alsa-utils
    - apache2-utils
    - autossh
    - awesome
    - awesome-extra
    - caja
    - cifs-utils
    - clang-format
    - cmake
    - code
    - colortail
    - dbus
    - debootstrap
    - default-jdk
    - di
    - dnsutils
    - dstat
    - entr
    - fcitx
    - fcitx-googlepinyin
    - fcitx-ui-light
    - fio
    - firefox
    - fiu-utils
    - fontforge
    - fping
    - g++
    - gcc-doc
    - google-chrome-stable
    - google-perftools
    - gradle
    - gufw
    - hdparm
    - hsetroot
    - htop
    - httpie
    - httrack
    - iftop
    - iotop
    - lftp
    - linux-headers-amd64
    - linux-image-amd64
    - linux-tools
    - lm-sensors
    - locate
    - lshw
    - lsof
    - make
    - manpages-dev
    - mate-desktop-environment-core
    - mate-utils
    - mdadm
    - mtr
    - mupdf
    - mycli
    - netcat
    - nginx
    - nmap
    - nodejs
    - ntfs-3g
    - ntpdate
    - p7zip-full
    - parallel
    - pluma
    - pm-utils
    - pppoeconf
    - psmisc
    - pulseaudio
    - python3.7
    - qbittorrent
    - redis-server
    - rinetd
    - rlwrap
    - rsync
    - rxvt-unicode-256color
    - samba
    - smbclient
    - smplayer
    - ssh
    - sshfs
    - sshpass
    - start-pulseaudio-x11
    - strace
    - sudo
    - supervisor
    - sysbench
    - syslog-ng
    - sysstat
    - systemd-sysv
    - tcpdump
    - time
    - tlp
    - tlp-rdw
    - tmux
    - tree
    - tsocks
    - unrar
    - unzip
    - valgrind
    - viewnior
    - vifm
    - vim-gtk
    - vsftpd
    - wicd-gtk
    - wpasupplicant
    - wput
    - wrk
    - x11-xkb-utils
    - x11-xserver-utils
    - xclip
    - xdg-user-dirs
    - xorg
    - xsel
    - yapf

  - name: check built-in tools
    shell: command -v {{item}}
    with_items:
    - getconf
    - ipcs
    - losetup
    - lscpu
    - lsusb
    - perf
    - pmap
    - trap

  - name: add user to sudoers
    template: src=templates/sudoers dest=/etc/sudoers.d/{{user}} mode=0440

  - name: download pt-summary
    get_url: url=http://percona.com/get/pt-summary dest=/usr/bin/pt-summary mode=0755

  - name: install phoronix-test-suite
    shell: "{{item}}"
    with_items:
    - "bin/axel http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_7.8.0_all.deb -o /var/cache/phoronix-test-suite.deb"
    - "dpkg -i /var/cache/phoronix-test-suite.deb"

  - name: create directories
    file: dest=/home/{{user}}/{{item}} state=directory recurse=yes owner={{user}}
    with_items:
    - .config/Code/User
    - .config/fontconfig
    - .vim/colors
    - .ssh

  - name: create symbolic link to dotfiles
    file: src=/home/{{user}}/.wizacfg/dotfiles/{{item}} dest=/home/{{user}}/.{{item}} state=link force=yes owner={{user}}
    with_items:
    - Xdefaults
    - asoundrc
    - bashrc
    - config/Code/User/keybindings.json
    - config/Code/User/settings.json
    - config/fontconfig/fonts.conf
    - gitconfig
    - ssh/config
    - tmux.conf
    - vim/colors/dante.vim
    - vimrc
    - xinitrc

  - name: create directories
    file: dest=/{{item}} state=directory recurse=yes
    with_items:
    - etc/xdg/awesome
    - etc/X11/xorg.conf.d

  - name: create symbolic link to awesome rc.lua
    file: src=/home/{{user}}/.wizacfg/{{item}} dest=/{{item}} state=link force=yes
    with_items:
    - etc/X11/xorg.conf.d/70-synaptics.conf
    - etc/rc.local
    - etc/xdg/awesome/rc.lua

  - name: update ansible config
    lineinfile:
      dest: /etc/ansible/ansible.cfg
      regexp: {{item.regexp}}
      line: {{item.line}}
      insertafter: '^\[default\]'
    with_items:
    - { regexp: '^callback_whitelist\s{0,}=', line: 'callback_whitelist = profile_tasks' }
    - { regexp: '^retry_files_enabled\s{0,}=', line: 'retry_files_enabled = False' }

  - name: remove apt packages
    apt: name={{item}} state=absent
    with_items:
    - lightdm
    - xscreensaver
