- hosts: localhost

  tasks:
    - name: create user
      user: name={{user}} state=present group=root shell=/bin/bash

    - name: change file mode of this repo
      file:
        dest: /home/{{user}}/.sysconf
        state: directory
        recurse: yes
        owner: "{{user}}"

    - name: locale-gen
      locale_gen: name={{item}} state=present
      with_items:
        - en_US.UTF-8
        - zh_CN
        - zh_CN.GB18030
        - zh_CN.GBK
        - zh_CN.UTF-8

    - name: create symbolic link to apt sources.list
      file: src=/home/{{user}}/.sysconf/{{item}} dest=/{{item}} state=link force=yes
      with_items:
        - etc/apt/sources.list.d/default.list
        - etc/apt/sources.list.d/google-chrome.list
        - etc/apt/sources.list.d/vscode.list

    - name: add apt keys
      shell: apt-key adv --keyserver keyserver.ubuntu.com --recv {{item}}
      with_items:
        - 7EA0A9C3F273FCD8 # aliyun docker
        - 1655A0AB68576280 # node
        - 425956BB3E31DF51 # deepin
        - 6494C6D6997C215E # chrome
        - 6A030B21BA07F4FB # aliyun kubernetes
        - EB3E94ADBE1229CF # vscode

    - name: install apt packages
      apt:
        update_cache: yes
        install_recommends: no
        name:
          - ack-grep
          - acpi
          - alsa-oss
          - alsa-tools
          - alsa-utils
          - apache2-utils
          - autossh
          - bash-completion
          - cifs-utils
          - colortail
          - debootstrap
          - di
          - dnsutils
          - docker-ce
          - dstat
          - entr
          - expect
          - f2fs-tools
          - fio
          - fiu-utils
          - fping
          - g++
          - gcp
          - grub2-common
          - haproxy
          - hdparm
          - hsetroot
          - htop
          - httrack
          - iftop
          - im-config
          - iotop
          - less
          - lftp
          - lm-sensors
          - locate
          - lshw
          - lsof
          - m4
          - make
          - manpages-dev
          - mtr
          - netcat
          - nethogs
          - nfs-common
          - nginx
          - nmap
          - nodejs
          - ntfs-3g
          - ntpdate
          - p7zip-full
          - parallel
          - pm-utils
          - pppoeconf
          - psmisc
          - pulseaudio
          - putty-tools
          - python3-pip
          - python3-setuptools
          - rcconf
          - rinetd
          - rlwrap
          - rsync
          - samba
          - smbclient
          - software-properties-common
          - ssh
          - sshfs
          - sshpass
          - strace
          - supervisor
          - sysbench
          - syslog-ng
          - sysstat
          - systemd-sysv
          - tlp
          - tlp-rdw
          - wpasupplicant

    - name: install cli tools
      apt:
        name:
          - apt-file
          - cmake
          - cmatrix
          - curl
          - jq
          - time
          - tmux
          - tree
          - tsocks
          - unrar-free
          - unzip
          - upower
          - valgrind
          - vim
          - whois
          - wput
          - wrk
          - yamllint

    - name: check built-in tools
      shell: command -v {{item}}
      with_items:
        - getconf
        - ipcs
        - losetup
        - lscpu
        - lsusb
        - pmap
        - trap

    - name: install database packages
      apt:
        name:
          - mycli
          - mysql-client
          - redis-server

    - name: install ocaml packages
      apt:
        install_recommends: no
        name:
          - menhir
          - ocaml
          - opam
          - utop

    - name: set pip index url
      shell: pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

    - name: install python packages
      pip:
        name:
          - ansible==2.9.9
          - base58==2.0.0
          - docker==4.2.1
        executable: pip3

    - name: install desktop
      apt:
        name:
          - awesome
          - awesome-extra
          - code
          - google-chrome-stable
          - gtk-theme-switch
          - leafpad
          - palemoon
          - qbittorrent
          - qpdfview
          - rxvt-unicode-256color
          - viewnior
          - wps-office
          - x11-xkb-utils
          - x11-xserver-utils
          - xdg-user-dirs
          - xfce4-panel
          - xfce4-session
          - xorg
          - xsel
          - xserver-xorg-input-all
          - xserver-xorg-input-kbd
          - xserver-xorg-input-synaptics
          - xtrlock
          #
          - libdtkwidget-dev=2.0.9.17-1
          - deepin-screenshot=4.1.8-1
          #
          - libva2=2.4.0-1
          - smplayer

    - name: install input method
      apt:
        name:
          - fcitx
          - fcitx-config-gtk
          - fcitx-frontend-gtk3
          - fcitx-googlepinyin
          - fcitx-modules
          - fcitx-tools
          - fcitx-ui-classic
          - fcitx-ui-light
          - libgtk-3-bin

    - name: conflicted packages
      apt:
        name:
          - fontforge
          - wicd-gtk
      when: false

    - name: remove apt packages
      apt:
        state: absent
        autoremove: yes
        purge: yes
        name:
          - apport
          - blueman
          - clipit
          - cups-*
          - gnome-*
          - lightdm
          - mate-*
          - nm-tray
          - packagekit
          - pidgin
          - snapd
          - system-config-printer
          - thunderbird
          - tracker
          - update-notifier
          - usbmuxd
          - volumeicon-alsa
          - whoopsie
          - xfce4-power-manager
          - xfce4-screensaver
          - xfdesktop4
          - xscreensaver
          - yad

    - name: install npm packages
      shell: "npm install -g {{item}}"
      with_items:
        - http-proxy-to-socks

    - name: create etc directories
      file: dest=/{{item}} state=directory recurse=yes
      with_items:
        - etc/X11/xorg.conf.d
        - etc/apt/apt.conf.d
        - etc/fonts/conf.d
        - etc/security/limits.d
        - etc/supervisor/conf.d
        - etc/xdg/awesome

    - name: create symbolic link to global config
      file: src=/home/{{user}}/.sysconf/{{item}} dest=/{{item}} state=link force=yes
      with_items:
        - etc/X11/xorg.conf.d/99-synaptics.conf
        - etc/apt/apt.conf.d/99default
        - etc/fonts/conf.d/99-default.conf
        - etc/rc.local
        - etc/supervisor/conf.d/unix_http_server.conf
        - etc/xdg/awesome/rc.lua

    - name: create template config
      template: src={{item}}.tpl dest=/{{item}} mode=0440
      with_items:
        - etc/security/limits.d/default.conf
        - etc/sudoers.d/default
        - etc/supervisor/conf.d/shadowsocks.conf

    - name: remove font dir
      lineinfile:
        dest: /etc/fonts/fonts.conf
        regexp: '^\s{0,}<dir'
        state: absent

    - name: add font dir
      lineinfile:
        dest: /etc/fonts/fonts.conf
        line: "\t{{item}}"
        insertafter: "<fontconfig"
      with_items:
        - "<dir>~/.fonts</dir>"

    - name: update tsocks config
      lineinfile:
        dest: /etc/tsocks.conf
        regexp: '^server\s{0,}='
        line: "server = 127.0.0.1"

    - name: disable splash screen
      lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT\s{0,}='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'

    - name: update grub config
      command: update-grub2

    - name: update systemd logind.conf
      lineinfile:
        dest: /etc/systemd/logind.conf
        regexp: '^{{item.key}}\s{0,}='
        line: "{{item.key}}={{item.value}}"
      with_items:
        - { key: "HandleLidSwitch", value: "ignore" }
        - { key: "HandlePowerKey", value: "suspend" }

    - name: disable grp:alt_shift_toggle
      shell: sed -i -e 's/grp:alt_shift_toggle,\?//g' /etc/default/keyboard

    - name: replace xfwm4 with awesome
      replace:
        path: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml
        regexp: "xfwm4"
        replace: "awesome"

    - name: set fs.inotify.max_user_watches
      sysctl:
        name: fs.inotify.max_user_watches
        value: "524288"

    - name: create user directories
      file: dest=/home/{{user}}/{{item}} state=directory recurse=yes owner={{user}}
      with_items:
        - .config/Code/User
        - .ssh

    - name: create symbolic link to user config
      file: src=/home/{{user}}/.sysconf/dotfiles/{{item}} dest=/home/{{user}}/.{{item}} state=link force=yes owner={{user}}
      with_items:
        - Xdefaults
        - bashrc
        - config/Code/User/keybindings.json
        - config/Code/User/settings.json
        - gitconfig
        - ssh/config
        - tmux.conf
        - vimrc
        - xinitrc

    - name: copy modified background
      copy:
        src: dotfiles/config/background.png
        dest: /usr/share/awesome/themes/default/background.png
        remote_src: yes

    - name: install vscode extensions
      shell: "code --install-extension {{item}}"
      with_items:
        - freebroccolo.reasonml
        - hediet.vscode-drawio
        - henriiik.vscode-sort
        - jeff-hykin.better-dockerfile-syntax
        - joaompinto.asciidoctor-vscode
        - michelemelluso.code-beautifier
        - mikeburgh.xml-format
        - ms-python.python
        - octref.vetur
        - redhat.vscode-yaml
        - shd101wyy.markdown-preview-enhanced
        - tobiasalthoff.atom-material-theme
        - vscodevim.vim
        - vscoss.vscode-ansible
      become: yes
      become_user: "{{user}}"
