#!/bin/sh

# run with sudo

set -e -x

HOME="/home/wiza"
PWD=$(cd $(dirname $0) && pwd)

mv /etc/locale.gen /etc/locale_gen
cp $PWD/locale.gen /etc/locale.gen
locale-gen

if [ "`grep meepo-1 /etc/hosts`" = "" ]; then
  cat $PWD/hosts >> /etc/hosts
fi

DEB_MIR="deb http://mirrors.ustc.edu.cn/debian/ sid main contrib non-free"
echo $DEB_MIR > /etc/apt/sources.list
apt-get update && apt-get upgrade -y

apt-get install -y --no-install-recommends \
                linux-headers-amd64 linux-image-amd64 \
                sudo make unzip unrar \
                xfce4-session xorg \
                awesome awesome-extra \
                wpasupplicant

if [ $# -eq 1 ] && [ $1 = '-full' ]; then
apt-get install -y --no-install-recommends \
                alsa-base alsa-oss alsa-tools alsa-utils \
                ack-grep axel cmake dbus di dstat \
                erlang-base-hipe erlang-inets erlang-xmerl \
                fio fiu-utils fonts-wqy-microhei \
                g++ gcc-doc gufw \
                hdparm hsetroot htop httpie httrack \
                iftop iotop lftp linux-tools lm-sensors lshw \
                mtr manpages-dev mupdf nmap ntfs-3g ntp \
                p7zip-full parallel pcmanfm pm-utils pppoeconf \
                ristretto rinetd rsync \
                samba scim-pinyin smbclient ssh strace sysstat \
                tcpdump time tmux tree tsocks \
                valgrind vifm vim-gtk vlc vsftpd \
                wput xsel xfce4-terminal
fi

for dir in .fonts local misc repos tmp; do
  mkdir -p $HOME/$dir
done

if [ "`grep Desktop /etc/crontab`" = "" ]; then
  echo "* * * * *  wiza  rm -df /home/wiza/Desktop" >> /etc/crontab
fi

grep "<prefer>" /etc/fonts/conf.d/*.conf \
| awk -F: '{print $1}' | uniq | xargs -I_x mv _x _x.bak
ln -sf $PWD/60-latin.conf     /etc/fonts/conf.d/
ln -sf $PWD/65-nonlatin.conf  /etc/fonts/conf.d/
ln -sf $PWD/69-unifont.conf   /etc/fonts/conf.d/

VUNDLE=$HOME/.vim/bundle/vundle
mkdir -p $VUNDLE && rm -r $VUNDLE
git clone -b master --depth 1 https://github.com/gmarik/vundle.git $VUNDLE

ln -sf $PWD/backup          /usr/bin/
ln -sf $PWD/after-boot      /usr/bin/
ln -sf $PWD/gccrun          /usr/bin/
ln -sf $PWD/shadowsocks     /usr/bin/
ln -sf $PWD/keycool.sh      /usr/bin/keycool
ln -sf $PWD/.xinitrc        $HOME/
ln -sf $PWD/.bashrc         $HOME/
ln -sf $PWD/.vimrc          $HOME/
ln -sf $PWD/.dircolors      $HOME/
ln -sf $PWD/.tmux.conf      $HOME/
ln -sf $PWD/.gitconfig      $HOME/
ln -sf $PWD/.asoundrc       $HOME/

mkdir -p $HOME/.vim/colors
cp $PWD/dante.vim           $HOME/.vim/colors/

set +x

echo "visudo# wiza ALL=(ALL) NOPASSWD: ALL"

exit 0

# useful tools
# getconf
# google-perftools
# hdparm --fibmap
# ipcs
# libhugetlbfs    # hugeadm, hugectl, pagesize
# losetup
# lscpu
# lsof
# lsusb
# mdadm
# ncat
# perf
# pmap
# pstree
# pt-summary    # wget http://percona.com/get/pt-summary
# setxkbmap
# ss
# stat
# xev
# xmodmap
