- name: disable services
  service:
    name: "{{item}}"
    state: stopped
    enabled: false
  with_items:
    - snapd
    - snapd.seeded
    - snapd.socket
    - systemd-resolved
  ignore_errors: true

- name: uninstall packages
  apt:
    state: absent
    name:
      - bluez
      - cloud-init
      - evolution-data-server
      - pcp
      - wireplumber
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr

- name: clean apt cache
  apt:
    autoremove: true
    purge: true
    clean: true

- name: disable execution
  file:
    path: /usr/bin/{{item}}
    mode: 400
  with_items:
    - cinnamon-screensaver
    - csd-clipboard
    - csd-keyboard
    - csd-media-keys
    - csd-screensaver-proxy
    - nemo-desktop
  ignore_errors: true
