- name: install cli tools
  apt:
    name:
      - ack-grep
      - aha
      - apt-file
      - autossh
      - cargo
      - chrony
      - cmake
      - cmatrix
      - cpufrequtils
      - cpulimit
      - curl
      - dconf-cli
      - di
      - docker-ce
      - fdisk
      - fish
      - fping
      - git-extras
      - gnupg1
      - htop
      - httrack
      - icdiff
      - iftop
      - inotify-tools
      - iotop
      - iperf3
      - jq
      - less
      - mariadb-client
      - mtr
      - ncal
      - nethogs
      - npm
      - postgresql-client
      - pv
      - python3-pip
      - rar
      - redis-tools
      - sqlite3
      - time
      - tmux
      - tree
      - tsocks
      - uidmap
      - unrar
      - unzip
      - upower
      - valgrind
      - whois
      - wput
      - yamllint
      - zstd

- name: check built-in commands
  shell: command -v {{item}}
  with_items:
    - getconf
    - ipcs
    - losetup
    - lscpu
    - lsusb
    - pmap
    - trap

- name: remove useless git commands
  file:
    path: /usr/bin/{{item}}
    state: absent
  with_items:
    - git-abort
    - git-alias
    - git-archive-file
    - git-authors
    - git-commits-since
